# Generated by Django 2.0.5 on 2018-05-22 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dostdict', '0002_remove_word_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='created_date',
        ),
    ]
