# Generated by Django 2.0.5 on 2018-05-22 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dostdict', '0003_remove_word_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='meaning',
        ),
    ]
